### PR TITLE
Update notification message when starting KA Lite server in windows application.

### LINKED ISSUE #456: Windows 10: Static assets are not consistently collected during installation
## Summary

We had a couple of reports of the same issue, seems to be Windows 10 specific?

https://community.learningequality.org/t/ka-lite-doesnt-serve-javascript-assets-in-windows-10/246/8

## Version

 - Installer: Windows 10
 - Version: 0.17.0 - 0.17.1

## Screenshots

blah

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary

> This will notified the user to wait, When starting the KA Lite server.

## Issues addressed

Fixes #456

### CODE REVIEW

**Comment by benjaoming** [comment]
@mrpau-richard build failure is because of [the Travis update](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch), I've fixed it in the latest `master` a `0.17.x` branch, so if you update your PR, it will work.

**Comment by benjaoming** [comment]
@mrpau-richard see above regarding getting the tests to work ^

**Comment by mrpau-richard** [comment]
@radinamatic I think the user must manually set it's duration. I found some of instructions [here](http://www.tech-recipes.com/rx/25996/windows-8-increase-notification-display-time/)

**Comment by radinamatic** [comment]
Ok, thanks for investigating this!

**Comment by mrpau-richard** [comment]
Merging this.

**Pull request merged**
