### PR TITLE
Fix KA Lite Mac application high CPU usage .

### LINKED ISSUE #445: KA-Lite High CPU Usage on Mac OSX Sierra
_From @andydupont on March 23, 2017 15:13_

## Summary

KA-Lite is contantly using large CPU % when started but idle

## System information

 - Operating system: Mac OSX Sierra (10.12.3)
 - Version: 0.17
 - Browser: N/A

## How to reproduce

1. Start KA-Lite App
2. Open Activity Monitor and sort on % CPU 

## Screenshots
screen shot 2017-03-23 at 10 50 40 am

## Real-life consequences 

I assumed there was some kind of indexing going on so I let it run overnight, but it is still at high CPU usage after 12 hours. We are using this in a remote area where power is limited. The CPU is consuming lots of power doing something. Will this stop after a while?

_Copied from original issue: learningequality/ka-lite#5426_

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary

> This fixes the KA Lite Mac application high CPU usage.

## Issues addressed

Fixes #445 

Here's the [osx installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMVXNLZVlYOFFMaTQ) to test this PR.

/cc @radinamatic @cpauya

### CODE REVIEW

**Comment by mrpau-richard** [comment]
@radinamatic can you verify the fix on this PR.

**Comment by radinamatic** [comment]
Tested this latest installer, and couldn't see high CPU usage... 👍 
Firefox would get worked up a bit with videos & exercises, but KA Lite process never goes higher than a couple of percentages!

sierra__start___running_

However, I couldn't download contentpacks, CORS error again, but didn't we jump the gun with the 0.18 release? 😛

**Comment by mrpau-richard** [comment]
@radinamatic I built the mac installer at KA Lite develop branch that's why it's version is 0.18.x. I will build another installer base in KA Lite 0.17.x branch.

**Comment by radinamatic** [comment]
It's good to go then, @cpauya ! 👍

**Comment by mrpau-richard** [comment]
@radinamatic Here's the new [mac installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMRUJOQVdlOEdDME0) if you want to test it again.

**Comment by radinamatic** [comment]
Installed, and played with videos and exercises, CPU usage still good, so this issue seems to be resolved!

I couldn't install contentpack from the UI, guessing it's still a version issue 'cause it installed OK from the command line... 😉

**Comment by benjaoming** [comment]
Oh interesting, @mrpau-richard could you explain more about how an unclosed file handle 1) doesn't get garbage collected and 2) causes such high CPU usage? It sounds really weird.. what I mean is that if we are going to announce that we have solved the CPU leak publicly, it would be nice to have a bit of certainty that it's solved :)

**Comment by mrpau-richard** [comment]
@benjaoming the caused of the high CPU usage is that I did not properly handle the KA Lite logs into KA Lite mac application. It always open, read and using cpu when there's new log sting output from ``kalite`` commads without closing it. Here's the [reference](http://stackoverflow.com/questions/13747232/using-nstask-and-nspipe-causes-100-cpu-usage) that help me fixed this issue.

**Comment by benjaoming** [comment]
I see, thanks for explaining it @mrpau-richard. Tried googling it, and there doesn't seem to be a way for Objective C to garbage collect file handles.

**Comment by benjaoming** [comment]
@mrpau-richard was this mac installer built on 0.17.0 or the current 0.17.x branch?

https://drive.google.com/open?id=0B5Tyi-tRKOFMRUJOQVdlOEdDME0

My follow-up question: Can it be signed and released?

**Comment by mrpau-richard** [comment]
It's on KA Lite 0.17.x branch @benjaoming.
I will try to build a signed OSX installer in my local and upload it in google drive.

**Comment by benjaoming** [comment]
@mrpau-richard just remember to build it on the "0.17.0" tagged commit.

**Pull request merged**
