### PR TITLE
Allow user to import KA Lite database during upgrade.

### LINKED ISSUE #459: Allow user to import KA Lite database during upgrade process
## Summary

> This issue came up after allowing the user to use their KA Lite content path in this [PR](https://github.com/learningequality/ka-lite-installers/pull/442)

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary

> I created a dialog message that allow the user to import KA Lite database during upgrade.

## Issues addressed

Fixes #459 

Here's the [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMalVyNTFEN010OHc) for testing.

/cc @radinamatic  @benjaoming

### CODE REVIEW

**Comment by benjaoming** [comment]
@mrpau-richard sorry that there have been no reviews here

Could you explain why importing a database is only relevant during an upgrade?

**Comment by mrpau-richard** [comment]
@benjaoming I think the reason why I have this PR is when we allow the user to set there own KA Lite content path, it may also need to import there existing KA Lite database. I suggested it in this [PR](https://github.com/learningequality/ka-lite-installers/pull/442#issuecomment-303934115).

**Comment by mrpau-richard** [comment]
@benjaoming it's also applicable to import database during fresh installation. Sorry I did not get your question [here](https://github.com/learningequality/ka-lite-installers/pull/462#issuecomment-326426522).

**Comment by benjaoming** [comment]
@mrpau-richard would you say that this is safe to merge?

If an upgrade through the Windows Installer causes the database to be overwritten presently, then it would sound like a critical fix.

However, if the current behavior also keeps an existing database unharmed, then maybe we should skip this PR, seeing that we probably won't be able to maintain any possible bugs that it might cause (not saying that the code is bad, just that it's rather complex by nature) ?

**Comment by mrpau-richard** [comment]
@benjaoming I just re-tested this, During the upgrade it will overwrite the existing KA Lite database and replace with the new one that the user uploaded.

**Comment by benjaoming** [comment]
@mrpau-richard wasn't the old behavior during upgrade to keep the user's existing database?

I mean, the same as what would happen if you `pip install ka-lite` (first time) and then when an upgrade arrives `pip install ka-lite --upgrade`: You just get a newer version, but everything in `~/.kalite` remains the same...

**Comment by mrpau-richard** [comment]
@benjaoming Yeah, During upgrade the old KA Lite database remain. Unless the user uploaded a new one and it replace the existing database.

**Comment by benjaoming** [comment]
Thanks for the clarification @mrpau-richard -- then I would say that this issue is not important: **Replacing** the database while upgrading does not fit any use case that I know of. **Preserving** the database is the critical part, and if that's already covered, then I think it's okay to move on.

Would you be okay about closing this PR? We have a lot of stuff going on :)

**Comment by mrpau-richard** [comment]
I agree @benjaoming lets close this and move on.

**Pull request closed without merging**
