### PR TITLE
Can't start KA Lite server if port 8008 is occupied  

### LINKED ISSUE #131: Cannot start server if port 8008 is used.
**Branch** 0.15.x

**Target** master

**Expected Behavior** The app must warn the user that the server cannot start because port 8008 is used by another process.

**Current Behavior** When the "Start KA Lite" menu is clicked, there is no indicator or message that the server cannot start because port 8008 is used.  The user then is left guessing what is going on with the app.

When debugging under Xcode, the console log shows:

```
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

Port 8008 is occupied. Please close the process that is using it.
```

**Screenshots**
- Xcode output when "Start KA Lite" menu is clicked.
  screenshot 2015-08-12 23 27 39
- System menu of the "KA-Lite Monitor" app after "Start KA Lite" menu is clicked.
  screenshot 2015-08-12 23 29 44

**Possible Solution/s** 
1. Check if port 8008 is used and inform the user of such.
2. Show the output of the `kalite` executable when attempting to start the server.  This will inform the user that an error was encountered by the app.  To be addressed by #129.
3. Document the process that the user must manually close the process/app that is using port 8008.

**Related Issue/s**
- [Kill existing pyrun activity when resetting the kalite-monitor app.](https://github.com/learningequality/installers/issues/125)
- [OSX application performance issues.](https://github.com/learningequality/installers/issues/129)

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary
I created a notification to notify the user if port 8008 is occupied.
 
## Issues addressed
This fixes #131

@radinamatic can you test this PR using this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMZExKLWxMaUtSdGc)

To test it, Run the command `python -m SimpleHTTPServer 8008` in the command prompt before starting the KA Lite server.

It will show a notification when starting KA Lite and the port 8008 is occupied.
src7

### CODE REVIEW

**Comment by mrpau-richard** [comment]
@radinamatic use this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMaVJmdU40a3hob1E) to test this PR, I have new fixes in hardcoded path of KALITE_HOME path environment variable.

**Comment by radinamatic** [comment]
@mrpau-richard I've tested the latest installer, occupied port alert is in place and I can see the 

```
KALITE_PYTHON=\Python27\python.exe
KALITE_SCRIPT_DIR=\Python27\Scripts
```

environment variables, but no `KALITE_HOME`. 

msedge_-_win10_kalite_home


Let me know if there's anything else I can check!

**Comment by mrpau-richard** [comment]
@radinamatic I think it's fine even if the KALITE_HOME is not set because it's automatically default to `user/.kalite` path. @mrpau-eduard I think you can merge this PR.

**Comment by benjaoming** [comment]
Great work, let's get it merged and I'll remember to add a release note about it in KA Lite.

**Pull request merged**
